version: "3.8"
services:
  app:
    build: .
    image: realtyflow_app:latest
    restart: always
    env_file:
      - .env.production
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    volumes:
      - uploads:/usr/src/app/uploads
    networks:
      - rfnet

  worker:
    image: realtyflow_app:latest
    restart: always
    env_file:
      - .env.production
    command: ["node","dist/worker.js"]
    depends_on:
      - db
      - redis
    networks:
      - rfnet

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-crm_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-strongpassword}
      POSTGRES_DB: ${POSTGRES_DB:-crm_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rfnet

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - rfnet

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "8080:80"
    networks:
      - rfnet

volumes:
  pgdata:
  uploads:

networks:
  rfnet:
